### ISSUE TITLE
TLS Usage in readme?

### ISSUE THREAD

**Issue by tomelic** [tewarid/node-tcp-proxy#19]
I'm using this sample to run the project as an npm library:
```
var proxy = require("node-tcp-proxy");
var util = require("util");
var serviceHosts = ["nonhttps.com", "www.baidu.com"];
var servicePorts = [80, 443];
var newProxy = proxy.createProxy(8080, serviceHosts, servicePorts, {
    upstream: function(context, data) {
        console.log(util.format("Client %s:%s sent:",
            context.proxySocket.remoteAddress,
            context.proxySocket.remotePort));
        // do something with the data and return modified data
        return data;
    },
    downstream: function(context, data) {
        console.log(util.format("Service %s:%s sent:",
            context.serviceSocket.remoteAddress,
            context.serviceSocket.remotePort));
        // do something with the data and return modified data
        return data;
    },
    serviceHostSelected: function(proxySocket, i) {
        console.log(util.format("Service host %s:%s selected for client %s:%s.",
            serviceHosts[i],
            servicePorts[i],
            proxySocket.remoteAddress,
            proxySocket.remotePort));
        // use your own strategy to calculate i
        return i;
    }
});
```

Unencrypted data to `http://nonhttps.com` works as expected, but trying to intercept HTTPS or TCP+TLS traffic (e.g. browsing to `https://badidu.com` with browser pointing to the proxy, I get either a not secure error or a "page is empty" from the browser.

I also noticed there's certificates in the `node_modules/node-tcp-proxy` directory, not sure how they are taken for an account when project is used as a library but even installing them at trusted root CA won't make a difference.

I think it would be highly appreciable  if you could provide more usage details on the topic of HTTPS/TCP+TLS interceptions

**Comment by tewarid** [comment]
Your request to `https://localhost:8080` fails with a not secure error because the browser gets a server certificate from `www.baidu.com:443` with a different Subject Alternative/DNS Name i.e. baidu.com, whereas the browser is expecting it to be localhost.

I've added a TLS version of the logger example that should clarify usage of the `tls` option. I'm using a very crude scheme of url rewriting to translate `localhost:8080` to `www.google.com`. This proxy is not an http(s) proxy. Dedicated http(s) proxies do a much better job of url rewriting, handling redirects etc.

If you do not specify a certificate and its password using the `pfx` and  `passphrase` options, the proxy uses the `cert.pfx` file that is distributed in the package as a convenience. That certificate will be considered invalid by the browser unless `cert.cer` is in the root of trust. Since `cert.pfx` is well known, I recommend keeping 'cert.cer` in the root of trust for the shortest amount of time possible, and/or using your own certs.

Hope that helps.

**Comment by tomelic** [comment]
Thanks a lot for the help.

I'm a bit confused though about the subject alt name.

Although not expecting full HTTP/HTTPS support, I just want to see that the library can intercept basic browser traffic in these settings:

**Pre**: 
Browser proxy sending to localhost --> `node-tcp-proxy` --> https://google.com

**User**:
Browses to https://google.com, experiences the site normally but the proxy sees/modifies the data

This is possible, for example, in BurpSuite - which lets you install a certificate issued to a fake CA, and doesn't even have a subject alt name and yet is recognized as secure by browsers.

Any idea how to accomplish this using this library?

again big thanks for the support.

**Comment by tewarid** [comment]
This package may be used as a building block to create a [classical proxy](https://tools.ietf.org/html/rfc1919) that sniffs/intercepts browser traffic, as demonstrated by the tls-logger example, but the user/app is aware of the existence of a proxy.

The kind of proxy you're looking for is implemented by transparent http proxies such as [mitmproxy](https://mitmproxy.org/). I've not yet looked into supporting building transparent proxies with this package.

**Comment by tomelic** [comment]
Self correction - I now see that upon browsing to sites, burpsuite does dynamically generate a per-host certificate with correct alt name under the CA.

And I understand what you're saying about the classical proxy, thanks for the help and patience.
